/**************************************************
LEADTOOLS (C) 1991-2016 LEAD Technologies, Inc. ALL RIGHTS RESERVED.
This software is protected by United States and International copyright laws.
Any copying, duplication, deployment, redistribution, modification or other
disposition hereof is STRICTLY PROHIBITED without an express written license
granted by LEAD Technologies, Inc.. This notice may not be removed or otherwise
altered under any circumstances.
Portions of this product are licensed under US patent 5,327,254 and foreign
counterparts.
For more information, contact LEAD Technologies, Inc. at 704-332-5532 or visit
https://www.leadtools.com
**************************************************/
// Leadtools.ImageProcessing.Core.js
// Version:19.0.0.3
onmessage=function(a){Leadtools_ImageProcessing_Core_Main(a)};var _callback=null;
Leadtools_ImageProcessing_Core_Main=function(a){if(!a)throw Error("'eventIn' must not be null");var c=a;a.data?(c=a.data,_callback=postMessage):_callback=c.callback;if(!c.imageData)throw Error("'imageData' must not be null");if(!_callback)throw Error("'callback' must not be null");if(void 0==c.imageData.width||void 0==c.imageData.height)c.imageData.width=c.width,c.imageData.height=c.height;switch(c.command){case "MaxFilter":Leadtools_ImageProcessing_Core_MaxFilter(c);break;case "MinFilter":Leadtools_ImageProcessing_Core_MinFilter(c);
break;case "Despeckle":Leadtools_ImageProcessing_Core_Despeckle(c);break;case "MultiScaleEnhancement":Leadtools_ImageProcessing_Core_MultiScaleEnhancement(c);break;case "ResizeInterpolate":Leadtools_ImageProcessing_Core_ResizeInterpolate(c);break;case "ScaleToGray":Leadtools_ImageProcessing_Core_ScaleToGray(c);break;case "ResizeBilinear":Leadtools_ImageProcessing_Core_ResizeBilinear(c);break;case "CLAHE":Leadtools_ImageProcessing_Core_CLAHE(c);break;default:throw Error("Unrecognized image processing command: "+
c.command);}};var _perspective="TOP_LEFT",_progressData=null;
function increaseProgress(){null==_progressData.value&&(_progressData.value=_progressData.start,_progressData.count=0);_progressData.count++;var a=_progressData.start+(_progressData.end-_progressData.start)*(_progressData.count/_progressData.resultImageHeight);return L_ParseInt(a)>_progressData.value&&(_progressData.value=L_ParseInt(a),a={status:"Progress",percentage:_progressData.value},_progressData.value==_progressData.end&&(_progressData.value=null),_callback(a),a.abort)?!0:!1}
function L_ParseInt(a){return a|0}function AccValue(){this.Value=0}function AccRGBValue(){this.BValue=this.GValue=this.RValue=0}
function _scaleToGrayClass(){this._resizedHeight=this._resizedWidth=this._yR=this._xR=0;this._data32=this._smallData=null;this._smallDataIndex=0;this._smallDataPixelArray=this._data32PixelArray=null;this._sumLargeRowImageData=function(a,c){for(var b=0,d=L_ParseInt(a),f=0,e=0,h=0;b<this._resizedWidth;b++)f=b*this._xR,h=Math.floor(f),f=1-(f-h),e=1-f,this._smallData[this._smallDataIndex+b]+=Math.floor((this._data32[d+h]&255)*f*c),0.01<e&&(this._smallData[this._smallDataIndex+b]+=Math.floor((this._data32[d+
h+1]&255)*e*c));return 0};this._sumRowImageData=function(a,c,b){for(var d=Math.floor(this._xR-1),f=this._xR-(d+1),e=0,h=a,g=0,j=1,k=L_ParseInt(256*this._xR),m=L_ParseInt(256),f=L_ParseInt(256*f),n=this._resizedWidth,l=0,o=this._data32PixelArray,p;l<n;l++){p=b[l];e=0;for(j=1;j<=d;j++)e+=o[h+j<<2]<<8;1<m&&(e+=o[h<<2]*m);1<f&&(e+=o[h+j<<2]*f);p.Value+=e*c>>16;g+=k;h=a+(g>>8);m=256-(g&255);d=k-m>>8;f=k-((d<<8)+m)}return b};this.processImageData=function(a,c,b,d,f,e,h,g){if(!(f>=c||e>=b)){this._resizedWidth=
f;this._resizedHeight=e;var j=this._resizedWidth;this._smallData=Array(j);for(i=0;i<j;i++)this._smallData[i]=new AccValue;this._smallDataPixelArray=d;h?(this._xR=1/h,this._yR=1/(g?g:h)):(this._xR=c/f,this._yR=b/e);var h=1,g=Math.floor(this._yR-h),j=this._yR-(g+h),k=L_ParseInt(256*h),m=L_ParseInt(256*j);this._data32PixelArray=a;var n=a=0,l=0,n=0,o,p=o=l=l=0,d=0,r=this._smallData;if(f<=c&&e<=b)for(d=this._xR*this._yR;a<e;a++){this._smallDataIndex=a*f;1<k&&(r=this._sumRowImageData(o,k,r));for(l=1;l<=
g;l++)r=this._sumRowImageData(o+c*l,256,r);1<m&&(r=this._sumRowImageData(o+c*l,m,r));p=this._smallDataIndex+f<<2;l=this._smallDataIndex<<2;for(b=0;l<p;l+=4)h=r[b],this._smallDataPixelArray[l]=this._smallDataPixelArray[l+1]=this._smallDataPixelArray[l+2]=L_ParseInt(h.Value/d),this._smallDataPixelArray[l+3]=255,h.Value=0,b++;n+=this._yR;o=L_ParseInt(n);h=1-(n-o);g=L_ParseInt(this._yR-h);j=this._yR-(g+h);o*=c;k=256*h>>0;m=256*j>>0}else if(f<=c&&e>b){d=this._xR;for(a=0;a<e;a++){this._smallDataIndex=a*
f;for(l=0;l<f;l++)this._smallData[this._smallDataIndex+l]=0;n=a*this._yR;b=Math.floor(n);n=1-(n-b);l=1-n;b*=c;this._sumRowImageData(b,Math.floor(100*n));0.01<l&&this._sumRowImageData(b+c,Math.floor(100*l));p=this._smallDataIndex+f<<2;for(l=this._smallDataIndex<<2;l<p;l+=4)this._smallDataPixelArray[l]=this._smallDataPixelArray[l+1]=this._smallDataPixelArray[l+2]=Math.floor(this._smallData[l>>2]/d),this._smallDataPixelArray[l+3]=255}}else if(f>c&&e>b)for(a=0;a<e;a++){this._smallDataIndex=a*f;for(l=
0;l<f;l++)this._smallData[this._smallDataIndex+l]=0;n=a*this._yR;b=Math.floor(n);n=1-(n-b);l=1-n;b*=c;this._sumLargeRowImageData(b,n);0.01<l&&this._sumLargeRowImageData(b+c,l);p=this._smallDataIndex+f<<2;for(l=this._smallDataIndex<<2;l<p;l+=4)this._smallDataPixelArray[l]=this._smallDataPixelArray[l+1]=this._smallDataPixelArray[l+2]=Math.floor(this._smallData[l>>2]/d),this._smallDataPixelArray[l+3]=255}else if(f>c&&e<=b)for(;a<e;a++){this._smallDataIndex=a*f;for(l=0;l<f;l++)this._smallData[this._smallDataIndex+
l]=0;0.1<h&&this._sumLargeRowImageData(o,h);for(l=1;l<=g;l++)this._sumLargeRowImageData(o+c*l,1);0.1<j&&this._sumLargeRowImageData(o+c*l,j);p=this._smallDataIndex+f<<2;for(l=this._smallDataIndex<<2;l<p;l+=4)this._smallDataPixelArray[l]=this._smallDataPixelArray[l+1]=this._smallDataPixelArray[l+2]=Math.floor(this._smallData[l>>2]/d),this._smallDataPixelArray[l+3]=255;n+=this._yR;o=Math.floor(n);h=1-(n-o);g=Math.floor(this._yR-h);j=this._yR-(g+h);o*=c<<2}}}}
function _resizeBilinear(){this._resizedHeight=this._resizedWidth=this._yR=this._xR=0;this._data32=this._smallData=null;this._smallDataIndex=0;this._smallDataPixelArray=this._data32PixelArray=null;this._sumLargeRowImageData=function(a,c){for(var b=0,d=L_ParseInt(a),f=0,e=0,h=0;b<this._resizedWidth;b++)f=b*this._xR,h=Math.floor(f),f=1-(f-h),e=1-f,this._smallData[this._smallDataIndex+b]+=Math.floor((this._data32[d+h]&255)*f*c),0.01<e&&(this._smallData[this._smallDataIndex+b]+=Math.floor((this._data32[d+
h+1]&255)*e*c));return 0};this._sumRowImageData=function(a,c,b){for(var d=Math.floor(this._xR-1),f=this._xR-(d+1),e=0,h=0,g=0,j=a,k=0,m=1,n=256*this._xR,l=L_ParseInt(256),f=L_ParseInt(256*f),o=this._resizedWidth,p=0,r=this._data32PixelArray,q;p<o;p++){q=b[p];g=h=e=0;for(m=1;m<=d;m++)e+=r[j+m<<2]<<8,h+=r[(j+m<<2)+1]<<8,g+=r[(j+m<<2)+2]<<8;1<l&&(e+=r[j<<2]*l,h+=r[(j<<2)+1]*l,g+=r[(j<<2)+2]*l);1<f&&(e+=r[j+m<<2]*f,h+=r[(j+m<<2)+1]*f,g+=r[(j+m<<2)+2]*f);q.BValue+=e*c>>16;q.GValue+=h*c>>16;q.RValue+=g*
c>>16;k+=n;j=a+(L_ParseInt(k)>>8);l=256-(L_ParseInt(k)&255);d=n-l>>8;f=n-((d<<8)+l)}return b};this.processImageData=function(a,c,b,d,f,e,h,g){if(!(f>=c||e>=b)){this._resizedWidth=f;this._resizedHeight=e;var j=this._resizedWidth;this._smallData=Array(j);for(i=0;i<j;i++)this._smallData[i]=new AccRGBValue;this._smallDataPixelArray=d;h?(this._xR=1/h,this._yR=1/(g?g:h)):(this._xR=c/f,this._yR=b/e);var k=1,j=Math.floor(this._yR-k),m=this._yR-(j+k),k=L_ParseInt(256*k),n=L_ParseInt(256*m);this._data32PixelArray=
a;var d=a=0,l,o=l=m=0,h=0,g=this._smallData;if(f<=c&&e<=b)for(h=this._xR*this._yR;a<e;a++){this._smallDataIndex=a*f;1<k&&(g=this._sumRowImageData(l,k,g));for(m=1;m<=j;m++)g=this._sumRowImageData(l+c*m,256,g);1<n&&(g=this._sumRowImageData(l+c*m,n,g));o=this._smallDataIndex+f<<2;m=this._smallDataIndex<<2;for(b=0;m<o;m+=4)j=g[b],this._smallDataPixelArray[m]=L_ParseInt(j.BValue/h),this._smallDataPixelArray[m+1]=L_ParseInt(j.GValue/h),this._smallDataPixelArray[m+2]=L_ParseInt(j.RValue/h),this._smallDataPixelArray[m+
3]=255,j.BValue=0,j.GValue=0,j.RValue=0,b++;d+=this._yR;l=L_ParseInt(d);k=1-(d-l);j=L_ParseInt(this._yR-k);m=this._yR-(j+k);l*=c;k=256*k>>0;n=256*m>>0}}}}
Leadtools_ImageProcessing_Core_ResizeBilinear=function(a){var c=a.imageData,b=a.scaleX,d=a.scaleY,f=a.resultImage;a.useProgress?(_progressData={start:0,end:100},_progressData.resultImageHeight=a.height):_progressData=null;(new _resizeBilinear).processImageData(c.data,c.width,c.height,f.data,f.width,f.height,b,d);_callback&&_callback({status:"Completed",imageData:c,resultImage:f})};
Leadtools_ImageProcessing_Core_CLAHE=function(a){var c=a.imageData;a.useProgress?(_progressData={start:0,end:100},_progressData.resultImageHeight=c.height):_progressData=null;L_CLAHE(c,a.alpha,a.tilesize,a.tilehistcliplimit,a.binsnumber,a.flags,!0);_callback&&_callback({status:"Completed",imageData:c})};function findMinMax(a,c,b){for(var d=0,f=0,d=65536,e=f=0;e<a.height*a.width;e++)d=Math.min(d,a.data[e]),f=Math.max(f,a.data[e]);c.value=d;b.value=f}
function ScaleToFullRange(a,c,b,d,f){b=16777215/(b-c+1);d*=f;for(f=0;f<d;f++)a[f]=L_ParseInt((a[f]-c)*b)}function L_MEMCPY(a,c,b,d,f){for(var e=c;e<c+f;e++)a[e]=b[d],d++}function findSigmoidLookUpTable(a,c,b){for(var b=5*b+1,d=c[1]-c[0],f=1/(1+Math.exp(-b))-0.5,e=0;1E3>e;e++){var h=-1/b*Math.log(1/(f*(e/999)+0.5)-1);a[e]=L_ParseInt(Math.min(c[0]+h*d,c[1]))}}
function findexponentialLookUpTable(a,c,b){for(var d=c[1]-c[0],f=1-Math.exp(-b),b=-1/b,e=0;1E3>e;e++)a[e]=L_ParseInt(Math.min(c[0]+b*Math.log(1-Math.min(f*(e/999),0.99999))*d,c[1]))}function findNormalLookUpTable(a,c){for(var b=c[1]-c[0],d=0;1E3>d;d++)a[d]=L_ParseInt(Math.min(c[0]+d/999*b,c[1]))}function findRayleighLookUpTable(a,c,b){for(var d=c[1]-c[0],b=2*b*b,f=1-Math.exp(-1/b),e=0;1E3>e;e++)a[e]=L_ParseInt(Math.min(c[0]+Math.sqrt(-b*Math.log(1-Math.min(0.9999,f*(e/999))))*d,c[1]))}
function FindNearestLargerPowerOf2Number(a){for(var c=0;a>1<<c;)c++;return c}function clipHistogram(a,c,b){for(var d=0,f=0;f<b;f++)d+=Math.max(a[f]-c,0);for(var e=Math.floor(d/b),h=c-e,f=0;f<b;f++)a[f]>c?a[f]=c:a[f]>h?(d-=c-a[f],a[f]=c):(d-=e,a[f]=L_ParseInt(a[f]+e));for(f=0;0!=d;){e=L_ParseInt(Math.max(Math.floor(b/d),1));for(h=f;h<b&&!(a[h]<c&&(a[h]++,d--,1>d));h+=e);f++;f>=b&&(f=1)}}
function makeMapping(a,c,b,d,f,e){a[0]=c[0];for(var h=1;h<f;h++)a[h]=a[h-1]+c[h];for(h=0;h<f;h++)b[h]=e[L_ParseInt(999*a[h]/d)]}
function MakeClaheImage(a,c,b,d,f,e,h,g){g=Math.pow(2,g);if(1==b[0]||1==b[1])for(var b=0,c=c[0],j=24-h,h=0;h<f;h++){for(d=0;d<e;d++)a[d+b]=c[a[d+b]>>j]/g;b+=e}else for(var f=0,k=Array(2),m=Array(2),n=0,l=0,o=0;o<b[1]+1;o++){0==o?(n=L_ParseInt(d[0]/2),k[0]=0,k[1]=0):o==b[1]?(n=L_ParseInt(d[0]/2),k[0]=b[1]-1,k[1]=b[1]-1):(n=d[0],k[0]=o-1,k[1]=o);for(var p=0,r=0;r<b[0]+1;r++){0==r?(l=L_ParseInt(d[1]/2),m[0]=0,m[1]=0):r==b[0]?(l=L_ParseInt(d[1]/2),m[0]=b[0]-1,m[1]=b[0]-1):(l=d[1],m[0]=r-1,m[1]=r);var q=
c[k[0]*b[0]+m[0]],s=c[k[0]*b[0]+m[1]],u=c[k[1]*b[0]+m[0]],w=c[k[1]*b[0]+m[1]],v=1/L_ParseInt((n-1)*(l-1)),j=24-h,t=f*e,y=n-1+1,z=-1,x=0,x=x-e,D=l-1,A=0,B=0,C=0,E=0,H=0,G,F;if(q==s&&q==u&&q==w)for(G=0;G<n;G++){x+=e;for(F=0;F<l;F++)a[t+p+F+x]=L_ParseInt(q[a[t+p+F+x]>>j]/g)}else for(G=0;G<n;G++){y--;z++;x+=e;A=y*D;B=0;C=z*D;for(F=E=0;F<l;F++)H=a[t+p+F+x]>>j,a[t+p+F+x]=L_ParseInt((A*q[H]+B*s[H]+C*u[H]+E*w[H])/g*v),A-=y,B+=y,C-=z,E+=z}p+=l}f+=n}}
function ToneMapping(a,c,b,d,f,e,h,g,j){var k,j=65536/j,m=Array(2),n=Array(2),l=Array(2),o=Array(2);o[0]=0;o[1]=0;m[0]=0;m[1]=16711680;n[0]=0;n[1]=16711680;l[0]=h;l[1]=h;n=Array(1E3);L_MEMSET(n,0,1E3);8==f?findSigmoidLookUpTable(n,m,e):2==f?findexponentialLookUpTable(n,m,e):4==f?findNormalLookUpTable(n,m):findRayleighLookUpTable(n,m,e);16711680<j&&(j=8388608);var f=FindNearestLargerPowerOf2Number(j),j=1<<f,p=L_ParseInt(c/h),r=L_ParseInt(b/h);o[0]=p;o[1]=r;e=L_AllocateUint32Array(h+1);m=L_AllocateUint32Array(h+
1);if(null==e||null==m)return!1;e[0]=0;for(var q=1;q<h+1;q++)e[q]=e[q-1]+p;m[0]=0;for(q=1;q<h+1;q++)m[q]=m[q-1]+r;p*=r;r=p>>f;g=r+L_ParseInt(1+g*(p-r));r=Array(h*h);if(null==r)return!1;for(q=0;q<h*h;q++){r[q]=L_AllocateUint32Array(j);if(null==r[q])return!1;L_MEMSET(r[q],0,j)}q=Array(j);if(null==q)throw Error("ERROR_NO_MEMORY");for(var s=null,u=24-f,w=0,v=0,t=k=0,y=0,z=0,x=0;x<h;x++){k=e[x];for(var t=e[x+1],D=k;D<t;D++){for(k=0;k<h;k++){s=r[z+k];w=m[k];for(v=m[k+1];w<v;w++)s[a[y+w]>>u]++}y+=b}z+=h}for(x=
0;x<h;x++)for(k=0;k<h;k++)s=r[x*h+k],clipHistogram(s,g,j),makeMapping(q,s,s,p,j,n);MakeClaheImage(a,r,l,o,c,b,f,d);return!0}
function L_CLAHE(a,c,b,d,f,e,h){var b=Math.max(1,Math.min(60,b)),g=1;1==(1&e)?g=1:2==(2&e)?g=2:4==(4&e)?g=4:8==(8&e)&&(g=8);if(null==a)throw Error("ERROR_NULL_PTR");e={};e.width=a.width;e.height=a.height;if(h){e.data=L_AllocateUint16Array(a.width*a.height);for(var j=0;j<a.width*a.height;j++)e.data[j]=a.data[4*j]<<8|a.data[4*j]}else{e.data=L_AllocateUint16Array(a.width*a.height);for(j=0;j<a.width*a.height;j++)e.data[j]=a.data[j]}var k=L_AllocateUint32Array(e.height*e.width);if(null==k)throw Error("ERROR_NO_MEMORY");
for(j=0;j<e.width*e.height;j++)k[j]=e.data[j];var m={value:0},n={value:0};findMinMax(e,m,n);ScaleToFullRange(k,m.value,n.value,e.width,e.height);var l=e.width,o=e.height,p=e.width+60,r=e.height+60,q=L_AllocateUint32Array(r*p);if(null==q)throw Error("ERROR_NO_MEMORY");for(var s=32*l,u=32*p,w=0,v=0,t=0;t<o;t++)L_MEMCPY(q,w,k,v,s/32),w+=p,v+=l;w=0-p;for(t=0;t<o;t++){w+=p;j=l-1;for(v=l;v<p;v++,j--)q[w+v]=q[w+j]}v=(o-1)*p;w=v+p;for(t=o;t<r;t++)L_MEMCPY(q,w,q,v,u/32),w+=p,v-=p;ToneMapping(q,r,p,32==!0?
16:8,g,c,b,d,f);for(t=v=w=0;t<o;t++)L_MEMCPY(k,v,q,w,s),w+=p,v+=l;c=(n.value-m.value)/65535;b=L_AllocateUint16Array(a.width);if(null==b)throw Error("ERROR_NO_MEMORY");d=0;f=65535;for(t=g=0;t<e.height;t++){for(v=0;v<e.width;v++)b[v]=L_ParseInt(k[v+g]*c+m.value),d=Math.max(d,b[v]),f=Math.min(f,b[v]);L_MEMCPY(e.data,t*e.width,b,0,e.width);g+=e.width}if(!0==h)for(j=0;j<a.width*a.height;j++)a.data[4*j]=e.data[j]>>8,a.data[4*j+1]=e.data[j]>>8,a.data[4*j+2]=e.data[j]>>8;else for(j=0;j<a.width*a.height;j++)a.data[j]=
e.data[j]}Leadtools_ImageProcessing_Core_MultiScaleEnhancement=function(a){var c=a.imageData;a.useProgress?(_progressData={start:0,end:100},_progressData.resultImageHeight=c.height):_progressData=null;MultiScaleEnhancementBitmap(c,a.contrast,a.edgeLevels,a.edgeCoefficient,a.latitudeLevels,a.latitudeCoefficient,a.flags,0,100);_callback&&_callback({status:"Completed",imageData:c})};
function MultiScaleEnhancementBitmap(a,c,b,d,f,e,h,g,j){var k=null,m=null,n={};n.data=L_AllocateUint8Array(4*a.width*a.height);n.width=a.width;n.height=a.height;var l=null,o={};o.data=L_AllocateUint8Array(4*a.width*a.height);o.width=a.width;o.height=a.height;L_CopyBitmap(o,a);var p=null,r=!1,q,s,u,w,v,t,y,z,x,D=null;-1!=b&&(D={},D.value=b);b=null;-1!=d&&(b={},b.value=d);d=null;-1!=f&&(d={},d.value=f);f=null;-1!=e&&(f={},f.value=e);q=L_ParseInt(Math.ceil(Math.log(Math.max(o.width,o.height))/Math.log(2)));
if(null!=D&&h&16&&(!D.value||D.value>q))throw Error("ERROR_INV_PARAMETER");if(null!=d&&h&32&&(!d.value||d.value>q))throw Error("ERROR_INV_PARAMETER");c=Math.min(1E4,c);p=L_AllocateInt32Array(256);h&16||h&32?e=!0:(e=!1,SetLUTEntries(p,256,c,0,0,0,null,null,null,null));r=!0;k=Array(q+1);L_MEMSET(k,0,q+1);m=Array(q+1);L_MEMSET(m,0,q+1);var A=null;v=g;t=L_ParseInt(0.9*(j-g)+0.5)+v;x=y=v;for(g=0;g!=q;g++){z=GetStatusNewPos(q,g,y,v,t);L_CopyBitmap(n,o);n.width=o.width;n.height=o.height;u=o.width;w=o.height;
l=L_ParseInt(u/2+0.5);s=L_ParseInt(w/2+0.5);null!=_progressData&&(x=L_ParseInt(40*(z-y)/100)+y,A=_progressData,_progressData=null);GaussianForRC(o);null!=A&&(_progressData=A,_progressData.end=x,_progressData.count=a.height-1,increaseProgress(),_progressData.count=0);null!=_progressData&&(x=L_ParseInt(45*(z-y)/100)+y,A=_progressData,_progressData=null);r?ReduceBitmapSize(o):L_SizeBitmap(o,l,s,1);null!=A&&(_progressData=A,_progressData.end=x,_progressData.count=a.height-1,increaseProgress(),_progressData.count=
0);l={};l.data=L_AllocateUint8Array(4*u*w);l.width=o.width;l.height=o.height;for(s=0;s<u*w;s++)l.data[4*s+3]=255;L_CopyBitmap(l,o);null!=_progressData&&(x=L_ParseInt(50*(z-y)/100)+y,A=_progressData,_progressData=null);r?EnlargeBitmapSize(l,u,w):L_SizeBitmap(l,u,w,0);null!=A&&(_progressData=A,_progressData.end=x,_progressData.count=a.height-1,increaseProgress(),_progressData.count=0);k[g]={};k[g].data=L_AllocateUint8Array(4*l.width*l.height);k[g].width=l.width;k[g].height=l.height;for(s=0;s<l.width*
l.height;s++)k[g].data[4*s+3]=255;L_CopyBitmap(k[g],l);null!=_progressData&&(x=L_ParseInt(65*(z-y)/100)+y,A=_progressData,_progressData=null);L_IntCombineBitmap(k[g],0,0,l.width,l.height,n,0,0,1280);null!=A&&(_progressData=A,_progressData.end=x,_progressData.count=a.height-1,increaseProgress(),_progressData.count=0);e&&SetLUTEntries(p,256,c,h,q,g,D,b,d,f);null!=_progressData&&(x=L_ParseInt(75*(z-y)/100)+y,A=_progressData,_progressData=null);L_IntRemapBitmapIntensity(k[g],p,256,0,0,100);null!=A&&(_progressData=
A,_progressData.end=x,_progressData.count=a.height-1,increaseProgress(),_progressData.count=0);m[g]={};m[g].data=L_AllocateUint8Array(4*n.width*n.height);m[g].width=n.width;m[g].height=n.height;for(s=0;s<n.width*n.height;s++)m[g].data[4*s+3]=255;L_CopyBitmap(m[g],n);null!=_progressData&&(x=L_ParseInt(90*(z-y)/100)+y,A=_progressData,_progressData=null);L_IntCombineBitmap(m[g],0,0,n.width,n.height,l,0,0,1280);null!=A&&(_progressData=A,_progressData.end=x,_progressData.count=a.height-1,increaseProgress(),
_progressData.count=0);null!=_progressData&&(x=L_ParseInt(100*(z-y)/100)+y,A=_progressData,_progressData=null);L_IntRemapBitmapIntensity(m[g],p,256,0,0,100);null!=A&&(_progressData=A,_progressData.end=x,_progressData.count=a.height-1,increaseProgress(),_progressData.count=0);y=z}v=t;t=j;x=v;for(g=q-1;-1!=g;g--)z=GetStatusNewPos(q,g,y,v,t),null!=_progressData&&(x=L_ParseInt(20*(z-y)/100)+y,A=_progressData,_progressData=null),r?EnlargeBitmapSize(o,k[g].width,k[g].height):L_SizeBitmap(o,k[g].width,k[g].height,
0),null!=A&&(_progressData=A,_progressData.end=x,_progressData.count=a.height-1,increaseProgress(),_progressData.count=0),null!=_progressData&&(x=L_ParseInt(80*(z-y)/100)+y,A=_progressData,_progressData=null),L_IntCombineBitmap(o,0,0,o.width,o.height,k[g],0,0,768),null!=A&&(_progressData=A,_progressData.end=x,_progressData.count=a.height-1,increaseProgress(),_progressData.count=0),k[g]=null,null!=_progressData&&(x=L_ParseInt(100*(z-y)/100)+y,A=_progressData,_progressData=null),L_IntCombineBitmap(o,
0,0,o.width,o.height,m[g],0,0,1024),null!=A&&(_progressData=A,_progressData.end=x,_progressData.count=a.height-1,increaseProgress(),_progressData.count=0),m[g]=null,y=z;L_CopyBitmap(a,o)}
function CombineBitmapExt(a,c,b,d,f,e,h,g,j){var k={RectSrc:{},RectDst:{},RectRes:{}},m=null,n,l={},o={},p={};o.value=(j&983040)>>16;l.value=(j&15728640)>>20;p.value=(j&251658240)>>24;if(0>l.value||3<l.value||0>o.value||3<o.value||0>p.value||3<p.value)throw Error("ERROR_INV_PARAMETER");if(!(0>=d||0>=f))if(n=!(!l.value||!o.value||!p.value),GetParametr(a,c,b,d,f,e,h,g,j,l,o,p,k)){f=!n&&(0==k.nDataFlage||256==k.nDataFlage||512==k.nDataFlage);b=L_AllocateUint8Array(a.width*k.nMaxCmp+4*k.nMaxCmp);c=L_AllocateUint8Array(e.width*
k.nMaxCmp+4*k.nMaxCmp);d=L_AllocateUint8Array(a.width*k.nMaxCmp+4*k.nMaxCmp);if(!f){m=Array(256);for(f=0;256>f;f++)m[f]=L_AllocateUint8Array(256);GetLookUpArray(m,k)}for(;k.RectRes.top<k.RectRes.bottom;)L_ImageProcessGet(a,b,k.RectDst.top),L_ImageProcessGet(e,c,k.RectSrc.top),L_ImageProcessGet(a,d,k.RectRes.top),Combine8(k,b,c,d,l.value,o.value,p.value,m,n),L_ImageProcessPut(a,d,k.RectRes.top),k.RectSrc.top++,k.RectDst.top++,k.RectRes.top++}}
function Combine8(a,c,b,d,f,e,h,g,j){var k=!j&&(0==a.nDataFlage||256==a.nDataFlage||512==a.nDataFlage);8192==a.nResFlage||12288==a.nResFlage?CombineBinary8(d,a.RectRes.left,a.RectRes.right,a.nResFlage,h,j):k?(0!=a.nDstFlage&&CombineBinary8(c,a.RectDst.left,a.RectDst.right,a.nDstFlage,f,j),0!=a.SrcFlage&&CombineBinary8(b,a.RectSrc.left,a.RectSrc.right,a.SrcFlage,e,j),CombineLog8(c,b,d,a),0!=a.nResFlage&&CombineBinary8(d,a.RectRes.left,a.RectRes.right,a.nResFlage,h,j)):j?CombineOpChan8(c,b,d,a,f,e,
h,g):CombineOp8(c,b,d,a,g)}function CombineOp8(a,c,b,d,f){for(var e=d.RectDst.left,h=d.RectSrc.left,g=d.RectRes.left,d=d.RectRes.right-d.RectRes.left;g<d;)b[g]=f[a[e]][c[h]],e++,h++,g++}function CombineOpChan8(a,c,b,d,f,e,h,g){f=d.RectDst.left+f;e=d.RectSrc.left+e;h=d.RectRes.left+h;for(d=d.RectRes.right-d.RectRes.left;h<d;)b[h]=g[a[f]][c[e]],f+=3,e+=3,h+=3}
function CombineLog8(a,c,b,d){var f,e,h,g,j,k;g=e=h=0;f=d.nDataFlage;e=d.RectSrc.left;h=d.RectDst.left;g=d.RectRes.left;switch(f){case 0:CombineLogAnd8(c,b,a,b);break;case 256:CombineLogOr8(c,b,a,b);break;case 512:CombineLogXor8(c,b,a,b)}j=d.RectRes.right-d.RectRes.left;k=d.RectRes.right-d.RectRes.left;d=0;h+=k;e+=k;for(g+=k;d<j;)0==f&&(b[g]=c[e]&a[h]),256==f&&(b[g]=c[e]|a[h]),512==f&&(b[g]=c[e]^a[h]),h++,e++,g++,d++}
function CombineLogAnd8(a,c,b){for(var d=0,f=0,e=0;f<ipScanIntEnd;)c[f]=a[d]&b[e],d++,e++,f++}function CombineLogOr8(a,c,b){for(var d=0,f=0,e=0;f<ipScanIntEnd;)c[f]=a[d]|b[e],d++,e++,f++}function CombineLogXor8(a,c,b){for(var d=0,f=0,e=0;f<ipScanIntEnd;)c[f]=a[d]^b[e],d++,e++,f++}
function CombineBinary8(a,c,b,d,f,e){switch(d){case 1:case 16:case 4096:e?CombineBinNOTChan8(a,c,b,f):CombineBinNOT8(a,c,b);break;case 3:case 48:case 12288:e?CombineBinONEChan8(a,c,b,f):CombineBinONE8(a,c,b);break;case 2:case 32:case 8192:e?CombineBinZEROChan8(a,c,b,f):CombineBinZERO8(a,c,b)}}function CombineBinZERO8(a,c,b){for(var d=c;d<b-c;d++)a[d]=0}function CombineBinZEROChan8(a,c,b,d){for(d=c+d;c<b;a+=3,c+=3)a[d]=0}function CombineBinONE8(a,c,b){for(var d=c;d<b-c;d++)a[d]=255}
function CombineBinONEChan8(a,c,b,d){for(d=c+d;c<b;d+=3,c+=3)a[d]=255}function CombineBinNOT8(a,c,b){var d,f=0,e,h;e=f+c;d=b-c;for(h=e+d;e<h;)a[e]=255-a[e],e++;c+=d;for(f+=c;c<b;c++)a[f]=255-a[f],f++}function CombineBinNOTChan8(a,c,b,d){for(d=c+d;c<b;d+=3,c+=3)a[d]=255-a[d]}
function GetLookUpArray(a,c){var b=0,d=1,f=0,e=0,h=1,g=0,j=0,k,m,n,l,o=0;switch(c.nDstFlage){case 16:b=255;break;case 48:f=255;break;case 32:d=0}switch(c.SrcFlage){case 1:e=255;break;case 3:g=255;break;case 2:h=0}switch(c.nResFlage){case 4096:j=255}for(m=0;256>m;m++)for(k=0;256>k;k++){l=b-Math.min(255,m*d+f);0>l&&(l=Math.abs(l));n=e-Math.min(255,k*h+g);0>n&&(n=Math.abs(n));switch(c.nDataFlage){case 0:o=j-(l&n);break;case 256:o=j-(l|n);break;case 512:o=j-(l^n);break;case 768:o=j-Math.min(255,l+n);
break;case 1024:case 1280:o=j-Math.max(0,l-n);break;case 3072:o=j-Math.abs(l-n);break;case 1536:o=j-L_ParseInt(l*n/255);break;case 1792:case 2048:o=n?j-Math.min(255,255*l/n):d?j-255:j-0;break;case 2304:o=j-L_ParseInt((l+n)/2);break;case 2560:o=j-Math.min(l,n);break;case 2816:o=j-Math.max(l,n)}0>o&&(o=Math.abs(o));1280==c.nDataFlage||2048==c.nDataFlage?a[k][m]=Math.min(255,o):a[m][k]=Math.min(255,o)}}
function GetParametr(a,c,b,d,f,e,h,g,j,k,m,n,l){l.nMaxCmp=3;l.SrcFlage=j&15;l.nDstFlage=j&240;l.nDataFlage=j&3840;l.nResFlage=j&61440;!k.value||!m.value||!n.value||1==l.nMaxCmp?(k.value=0,m.value=0,n.value=0):(k.value=3-k.value,m.value=3-m.value,n.value=3-n.value);l.RectDst.left=Math.min(d,c)*l.nMaxCmp;l.RectDst.right=Math.min(d,d+c)*l.nMaxCmp;l.RectSrc.left=Math.min(d,h)*l.nMaxCmp;l.RectSrc.right=Math.min(d,d+h)*l.nMaxCmp;l.RectDst.top=Math.min(f,b);l.RectDst.bottom=Math.min(f,f+b);l.RectSrc.top=
Math.min(f,g);l.RectSrc.bottom=Math.min(f,f+g);if(0>c||0>h)c<h?(l.RectSrc.left+=Math.abs(l.RectDst.left),l.RectDst.left=0):(l.RectDst.left+=Math.abs(l.RectSrc.left),l.RectSrc.left=0);if(0>b||0>g)b<g?(l.RectSrc.top+=Math.abs(l.RectDst.top),l.RectDst.top=0):(l.RectDst.top+=Math.abs(l.RectSrc.top),l.RectSrc.top=0);l.RectRes.left=l.RectDst.left;l.RectRes.right=Math.min(l.RectDst.right-l.RectDst.left,l.RectSrc.right-l.RectSrc.left)+l.RectDst.left;l.RectRes.top=l.RectDst.top;l.RectRes.bottom=Math.min(l.RectDst.bottom-
l.RectDst.top,l.RectSrc.bottom-l.RectSrc.top)+l.RectDst.top;return l.RectRes.left>=l.RectRes.right||l.RectRes.top>=l.RectRes.bottom?!1:!0}function IntCombineBitmap(a,c,b,d,f,e,h,g,j){CombineBitmapExt(a,c,b,d,f,e,h,g,j)}function L_IntCombineBitmap(a,c,b,d,f,e,h,g,j){IntCombineBitmap(a,c,b,d,f,e,h,g,j)}function EnlargeBitmapSize(a,c,b){EnlargeBitmapSizeInt(a,c,b)}
function EnlargeBitmapSizeInt(a,c,b){for(var d=Array(3),f=null,e=Array(3),h=0;3>h;h++)e[h]=L_AllocateUint32Array(256);var g=null,h=null,j,k,m,n,g=L_AllocateUint8Array(3*a.width+12);1!=a.width&&(f=a.width<<1,c=Math.max(f-1,Math.min(f,c)));1!=a.height&&(f=a.height<<1,b=Math.max(f-1,Math.min(f,b)));for(j=0;3>j;j++){d[j]=Array(4);for(f=0;4>f;f++)d[j][f]=L_AllocateUint32Array(3*a.width)}f={};f.data=L_AllocateUint8Array(4*c*b);for(h=0;h<c*b;h++)f.data[4*h+3]=255;f.width=c;f.height=b;h=L_AllocateUint8Array(3*
f.width+12);for(j=0;256>j;j++)e[0][j]=5*j,e[1][j]=25*j,e[2][j]=40*j;k=-1;m=0;for(j=-4;j<b;j++)if(n=j%2,n||(k!=m&&(m=Math.max(0,Math.min(a.height-1,k)),L_ImageProcessGet(a,g,m)),SetHolder08(d,g,e,a.width,3),k++),0<=j)n?DoExOddRows08(d,h,3,c):DoExEvenRows08(d,h,3,c),L_ImageProcessPut(f,h,j);a.width=f.width;a.height=f.height;L_CopyBitmap(a,f)}
function DoExEvenRows08(a,c,b,d){var f,e,h,g,j,k,m,n,l,o,p;e=g=j=o=p=0;var r,q,s,u,w=0;l=a[1][3];f=a[0][0];h=a[1][2];a=a[2][0];k=e+b;m=g+b;n=j+b;s=d%2?d:d-1;for(r=0;r<s;r++)if(w){for(u=0;u<b;u++)q=f[e]+f[k]+h[g]+h[m]+a[j]+a[n],e++,k++,g++,m++,j++,n++,q=L_ParseInt(q/100+0.5),c[p]=Math.min(255,q),p++;w--}else{for(u=0;u<b;u++)c[p]=Math.min(255,l[o]),p++,o++;w++}if(d!=s)for(u=0;u<b;u++)q=(f[e]<<1)+(h[g]<<1)+(a[j]<<1),e++,g++,j++,q=L_ParseInt(q/100+0.5),c[p]=Math.min(255,q),p++}
function SetHolder08(a,c,b,d,f){var e,h,g,j,k,m;e=a[0];a[0]=a[1];a[1]=a[2];a[2]=e;e=a[2][3];h=a[2][0];g=a[2][1];var a=a[2][2],n=0,l=0,o=0,p=0,r=0;for(j=0;j<d;j++)for(m=0;m<f;m++)k=c[n],n++,e[l]=k,l++,h[o]=b[0][k],o++,g[p]=b[1][k],p++,a[r]=b[2][k],r++}
function DoExOddRows08(a,c,b,d){var f,e,h,g,j,k;e=j=0;var m,n,l,o,p,r,q,s,u,w;n=o=s=u=0;var v,t,y,z,x=0;f=a[1][1];g=a[2][1];h=e+b;k=j+b;m=a[1][0];l=a[1][2];r=n+(2>=d?0:b);q=a[2][0];a=a[2][2];w=s+(2>=d?0:b);y=d%2?d-1:d-2;var D=0;for(z=0;z<b;z++)t=m[n]+l[o]+m[r]+q[s]+a[u]+q[w],n++,o++,p++,s++,u++,w++,t=L_ParseInt(t/100+0.5),c[D]=Math.min(255,t),D++;x++;n-=b;s-=b;for(v=1;v<y;v++)if(x){for(z=0;z<b;z++)t=f[e]+f[h]+g[j]+g[k],e++,h++,j++,k++,t=L_ParseInt(t/100+0.5),c[D]=Math.min(255,t),D++;x--}else{for(z=
0;z<b;z++)t=m[n]+l[o]+m[r]+q[s]+a[u]+q[w],n++,o++,p++,s++,u++,w++,t=L_ParseInt(t/100+0.5),c[D]=Math.min(255,t),D++;x++}if(2<d){r-=b;w-=b;for(z=0;z<b;z++)t=m[n]+l[o]+m[r]+q[s]+a[u]+q[w],n++,o++,p++,s++,u++,w++,t=L_ParseInt(t/100+0.5),c[D]=Math.min(255,t),D++;if(y+2==d)for(z=0;z<b;z++)t=f[e]+f[e]+g[j]+g[j],e++,j++,t=L_ParseInt(t/100+0.5),c[D]=Math.min(255,t),D++}}function ReduceBitmapSize(a){ReduceBitmapSizeInt(a)}
function ReduceBitmapSizeInt(a){var c=null,b=null,d=null,f,e,h,b=L_AllocateUint8Array(3*a.width+12);f=L_ParseInt(a.width/2+0.5);e=L_ParseInt(a.height/2+0.5);c={};c.data=L_AllocateUint8Array(4*f*e);for(d=0;d<f*e;d++)c.data[4*d+3]=255;c.width=f;c.height=e;d=L_AllocateUint8Array(3*c.width+12);for(h=0;h<e;h++)L_ImageProcessGet(a,b,h<<1),DoReduce8(b,d,f,3),L_ImageProcessPut(c,d,h);a.width=c.width;a.height=c.height;L_CopyBitmap(a,c)}
function DoReduce8(a,c,b,d){var f,e,h=0,g=0;for(f=0;f<b;f++){for(e=0;e<d;e++)c[h]=a[g],h++,g++;g+=d}}function GetStatusNewPos(a,c,b,d,f){var e,h=0;for(e=0;e<a;e++)h+=Math.pow(4,e);a=Math.pow(4,a-1-c)/h*(f-d);return Math.min(L_ParseInt(a+b+0.5),f)}
function SetLUTEntries(a,c,b,d,f,e,h,g,j,k){var m,n,l,o,h=null!=h?h.value:3,j=null!=j?j.value:5,g=null!=g?g.value/100:1.7;l=null!=k?k.value/100:1.4;k=1/(c-1);n=1-b/1E4;for(b=o=0;o<c;o++,b+=k)m=Math.pow(b,n),d&16&&e<h&&(m*=Math.pow(g,1-e/h)),d&32&&e>=f-j&&(m*=Math.pow(l,(f-e-j-1)/j)),m=Math.min(1,Math.max(0,m)),a[o]=L_ParseInt(m*(c-1)+0.5)}function L_CopyBitmap(a,c){for(var b=0;b<4*c.width*c.height;b++)a.data[b]=c.data[b]}function GaussianForRC(a){DoGaussianForRC(a,0,100)}
function DoGaussianForRC(a,c,b){var d;d=L_ParseInt((b-c)/2)+c;_perspective="TOP_LEFT";null!=_progressData&&(_progressData.start=c,_progressData.end=d,_progressData.resultImageHeight=L_GetHeight(a));ApplyGaussianForRCFilter(a);_perspective="LEFT_TOP";null!=_progressData&&(_progressData.start=Math.min(d+1,b),_progressData.end=b,_progressData.resultImageHeight=L_GetHeight(a));ApplyGaussianForRCFilter(a);_perspective="TOP_LEFT"}
function ApplyGaussianForRCFilter(a){var c=Array(3);L_MEMSET(c,0,3);var b=null,d=null,f,e,h,g,j={};L_GetHeight(a);g=L_GetWidth(a)-1;b=L_AllocateUint16Array(5);b[0]=b[4]=1;b[1]=b[3]=5;b[2]=8;d=L_AllocateUint8Array(3*L_GetWidth(a)+12);f=L_GetWidth(a);for(e=0;3>e;e++)c[e]=L_AllocateInt32Array(f);j.left=0;j.top=0;j.right=L_GetWidth(a);j.bottom=L_GetHeight(a);for(h=j.top;h<j.bottom;){for(e=0;3>e;e++)L_MEMSET(c[e],0,f);L_ImageProcessGet(a,d,h);AddLines8(c,d,b,3,g,2,j);AverageLines8(c,d,3,20,j);L_ImageProcessPut(a,
d,h);h++}}function AverageLines8(a,c,b,d,f){var e,h,g,j;for(j=0;j<b;j++){h=j+f.left*b;e=a[j];var k=f.left;for(g=f.left;g<f.right;g++)c[h]=L_ParseInt(Math.max(0,Math.min(255,e[k]/d))),h+=b,k++}}function AddLines8(a,c,b,d,f,e,h){var g,j,k,m,n,l,o,p,r,q,s;for(o=0;o<d;o++){g=a[o];var u=h.left;m=0;m+=o;for(p=h.left;p<h.right;){l=n=0;r=p-e;j=0<=r?m+r*d:m;q=p+e;k=q<f?m+q*d:m+f*d;for(s=0;s<e;s++)b[n]&&(l+=(c[j]+c[k])*b[n]),n++,0<=r&&(j+=d),q<=f&&(k-=d),r++,q--;l+=c[j]*b[n];g[u]=l;u++;p++}}}
function L_IntRemapBitmapIntensity(a,c,b,d,f,e){for(var h=null,h=L_AllocateUint32Array(b),g=0;g<b;g++)h[g]=c[g];IntRemapBitmapIntensity(a,h,b,d,f,e)}function IntRemapBitmapIntensity(a,c,b,d){d&256&&(d&16||CheckAndUpdateLUTData(a,c,b),RempBitmapNormal(a,c,b,c,b));d&256||CheckAndUpdateLUTData(a,c,b);RemapBitmapIntensity(a,c,d&15);d&256&&delete c}function RempBitmapNormal(a,c,b,d){d=L_AllocateUint32ArrayInit(b);for(a=0;a<b;a++)d[a]=c[a]}
function CheckAndUpdateLUTData(a,c,b){for(var d,a=0;a<b;a++){d=c[a];0>d&&(d+=b);if(0>d||d>=b)throw Error("ERROR INV PARAMETER");c[a]=d}}
Leadtools_ImageProcessing_Core_ScaleToGray=function(a){var c=a.imageData,b=a.scaleX,d=a.scaleY,f=a.resultImage;a.useProgress?(_progressData={start:0,end:100},_progressData.resultImageHeight=a.height):_progressData=null;(new _scaleToGrayClass).processImageData(c.data,c.width,c.height,f.data,f.width,f.height,b,d);_callback&&_callback({status:"Completed",imageData:c,resultImage:f})};
Leadtools_ImageProcessing_Core_ResizeInterpolate=function(a){var c=a.imageData,b=a.useProgress,d=a.width,f=a.height,e=a.type,h=null;"undefined"!=typeof a.resultImage&&null!=a.resultImage&&a.resultImage.width==d&&a.resultImage.height==f&&(h=a.resultImage);b?(_progressData={start:0,end:100},_progressData.resultImageHeight=a.height):_progressData=null;a=L_SizeBitmapInterpolate(c,h,d,f,e);_callback&&_callback({status:"Completed",imageData:c,resultImage:a})};
function L_SizeBitmapInterpolate(a,c,b,d,f){var e,h;e=null;if(0>=b||0>=d)throw Error("ERROR_INV_PARAMETER");e=a.width;h=a.height;if(b==e&&d==h)return null;switch(f){case 5:case 6:case 7:case 8:case 9:case 10:e=MiddleSpeedFilters(a,c,b,d,f);break;case 11:case 12:case 13:case 14:case 15:case 16:e=SlowSpeedFilters(a,c,b,d,f);break;case 17:e=BilinearResizeBitmap(a,c,b,d);break;case 18:e=BresenhamResizeBitmap(a,c,b,d);break;case 4:case 0:case 2:e=L_SizeBitmap(a,c,b,d,f);break;default:throw Error("ERROR_INV_PARAMETER");
}return e}function BresenhamResizeBitmap(a,c,b,d){var f;null!=c?pTempBitmap=c:(pTempBitmap={},pTempBitmap.data=L_AllocateUint8Array(4*b*d),pTempBitmap.width=b,pTempBitmap.height=d);for(c=0;c<b*d;c++)pTempBitmap.data[4*c+3]=255;c=a.width;f=a.height;b>=c&&d>=f?BresenhamUpSampleBitmap(a,pTempBitmap,b,d):b<=c&&d<=f?BresenhamDownSampleBitmap(a,pTempBitmap,b,d):b>c&&d<f?BresenhamDownHeightUpWidth(a,pTempBitmap,b,d):BresenhamDownWidthUpHeight(a,pTempBitmap,b,d);return pTempBitmap}
function BresenhamDownWidthUpHeight(a,c,b,d){var f=null,e,h,g,j=null,k=null,m=null,n=null,f=L_AllocateUint8Array(3*a.width+12);h=a.height;e=a.width;g=3*c.width;j=L_AllocateUint8Array(g);k=L_AllocateUint8Array(g);m=L_AllocateUint8Array(g);n=L_AllocateUint8Array(g);BresenhamDownWidthUpHeight8(f,c,a,3,e,h,d,b,g,j,k,m,n)}
function BresenhamDownWidthUpHeight8(a,c,b,d,f,e,h,g,j,k,m,n,l){var o,p,r,q,s,u,w,v,t;o=0;p=-1;r=0;s=L_ParseInt(h/2);w=f%g;u=L_ParseInt(f/g)*d;q=!0;if(3==d&&(L_ImageProcessGet(b,a,0),ColorScaleLine8(m,a,w,u,g,d),L_CopyArray(m,k,j),L_CopyArray(m,l,j),2>e)){for(v=0;v<h;v++)L_ImageProcessPut(c,k,v),L_CopyArray(l,k,j);return}f=h-1;for(v=0;v<f;v++)if(p!=o&&(p=o+1,p<e&&L_ImageProcessGet(b,a,p),p=o,3==d&&ColorScaleLine8(n,a,w,u,g,d),q=!0),r>=s&&q&&(3==d&&ColorLinesAverage8(m,n,k,g,d),q=!1),L_ImageProcessPut(c,
k,v),L_CopyArray(l,k,j),r+=e,r>=h)r-=h,o++,t=m,m=n,n=t,L_CopyArray(m,k,j),L_CopyArray(k,l,j);L_ImageProcessGet(b,a,o);3==d&&ColorScaleLine8(k,a,w,u,g,d);L_ImageProcessPut(c,k,v)}
function BresenhamDownHeightUpWidth(a,c,b,d){var f=null,e,h,g=null,j,k,m,n,l,o,f=L_AllocateUint8Array(3*a.width+12);h=a.height;e=a.width;g=L_AllocateUint8Array(3*c.width);o=l=n=0;j=h%d;k=L_ParseInt(h/d);m=L_ParseInt(b/2);L_ImageProcessGet(a,f,n);ColorAverageScaleLine8(g,f,m,e,b,3);for(h=0;h<d;h++)if(l!=n&&(L_ImageProcessGet(a,f,n),l=n,ColorAverageScaleLine8(g,f,m,e,b,3)),n+=k,L_ImageProcessPut(c,g,h),o+=j,o>=d)o-=d,n++}
function BresenhamDownSampleBitmap(a,c,b,d){var f=null,e,h,g=null,j,k,m,n,l,o,f=L_AllocateUint8Array(3*a.width+12);h=a.height;e=a.width;g=L_AllocateUint8Array(3*c.width);o=l=n=0;j=h%d;m=e%b;h=L_ParseInt(h/d);k=3*L_ParseInt(e/b);L_ImageProcessGet(a,f,n);ColorScaleLine8(g,f,m,k,b,3);for(e=0;e<d;e++)if(l!=n&&(L_ImageProcessGet(a,f,n),l=n,ColorScaleLine8(g,f,m,k,b,3)),n+=h,L_ImageProcessPut(c,g,e),o+=j,o>=d)o-=d,n++}
function ColorScaleLine8(a,c,b,d,f,e){var h,g,j,k;for(g=h=k=j=0;g<f;g++)a[j]=c[k],a[j+1]=c[k+1],a[j+2]=c[k+2],j+=e,k+=d,h+=b,h>=f&&(h-=f,k+=e)}function BresenhamUpSampleBitmap(a,c,b,d){var f=null,e,h,g,j=null,k=null,m=null,n=null,f=L_AllocateUint8Array(3*a.width+12);h=a.height;e=a.width;g=3*c.width;j=L_AllocateUint8Array(g);k=L_AllocateUint8Array(g);m=L_AllocateUint8Array(g);n=L_AllocateUint8Array(g);BresenhamInterpolation8(f,c,a,3,e,h,d,b,g,j,k,m,n)}
function BresenhamInterpolation8(a,c,b,d,f,e,h,g,j,k,m,n,l){var o,p,r,q,s,u,w,v,t;o=0;p=-1;r=0;u=L_ParseInt(h/2);w=L_ParseInt(g/2);s=!0;if(3==d&&(L_ImageProcessGet(b,a,0),ColorAverageScaleLine8(m,a,w,f,g,d),L_CopyArray(m,k,j),L_CopyArray(k,l,j),2>e)){for(v=0;v<h;v++)L_ImageProcessPut(c,k,v),L_CopyArray(l,k,j);return}q=h-1;for(v=0;v<q;v++)if(p!=o&&(p=o+1,p<e&&L_ImageProcessGet(b,a,p),p=o,3==d&&ColorAverageScaleLine8(n,a,w,f,g,d),s=!0),r>=u&&s&&(3==d&&ColorLinesAverage8(m,n,k,g,d),s=!1),L_ImageProcessPut(c,
k,v),L_CopyArray(l,k,j),r+=e,r>=h)r-=h,o++,t=m,m=n,n=t,L_CopyArray(m,k,j),L_CopyArray(k,l,j);L_ImageProcessGet(b,a,o);3==d&&ColorAverageScaleLine8(n,a,w,f,g,d);L_ImageProcessPut(c,n,v)}function ColorLinesAverage8(a,c,b,d,f){var e,h=0,g=0,j=0;for(e=0;e<d;e++)b[h]=a[g]+c[j]>>1,b[h+1]=a[g+1]+c[j+1]>>1,b[h+2]=a[g+2]+c[j+2]>>1,h+=f,g+=f,j+=f}
function ColorAverageScaleLine8(a,c,b,d,f,e){var h,g,j,k,m,n,l=L_AllocateUint8Array(3),o,p,r,q;n=e*(d-1);k=j=0;m=e;2>d&&(m=k);h=0;o=f-1;p=-1;r=0;q=!0;for(g=0;g<o;g++)if(p!=r&&(l[0]=c[k],l[1]=c[k+1],l[2]=c[k+2],p=r),h>=b&&q&&(l[0]=l[0]+c[m]>>1,l[1]=l[1]+c[m+1]>>1,l[2]=l[2]+c[m+2]>>1,q=!1),a[j]=l[0],a[j+1]=l[1],a[j+2]=l[2],j+=e,h+=d,h>=f)h-=f,k+=e,m+=e,r++,m>n&&(m=n),q=!0;a[j]=c[k];a[j+1]=c[k+1];a[j+2]=c[k+2]}
function BilinearResizeBitmap(a,c,b,d){var f,e,h=null;f=a.width;e=a.height;null!=c?h=c:(h={},h.data=L_AllocateUint8Array(4*b*d),h.width=b,h.height=d);for(c=0;c<b*d;c++)h.data[4*c+3]=255;b>=f&&d>=e?UpSampleBitmap(a,h,b,d):b<=f&&d<=e?DownSampleBitmap(a,h,b,d):b>f&&d<e?DownHieghtUpWidth(a,h,b,d):DownWidthUpHeight(a,h,b,d);return h}
function DownWidthUpHeight(a,c,b,d){var f=null,e=null,h,g,j={},k,m=null,n=null,l=null,o=null,p=null,r=null;k=null;var q,s,u=e=null,w={},v,t,y,f=L_AllocateUint8Array(3*a.width+12),e=L_AllocateUint8Array(3*a.width+12);g=a.height;h=a.width;v=L_ParseInt(h/2);t=3*b;y=3*c.width;q=(d-1)/(g-1);m=L_ParseInt(q+2);s=b>v?b/h:h/b;k=3*c.width*m;u=L_AllocateUint8Array(k);m=L_AllocateUint32Array(b);n=Array(g);o=L_AllocateUint32Array(d);b>v&&(l=L_AllocateUint32Array(h),k=b,p=L_AllocateUint32Array(k),L_MEMSET(p,0,
k));k=3*c.width;r=L_AllocateUint8Array(k);k=L_AllocateUint8Array(k);SetHorizentalBuffers(b,h,v,m,l,p,s);s=0;for(h=1;h<g;h++)s+=q,n[h]=s;n[0]=0;n[g-1]=d-1;SetYRatioBuffers(o,g,q,n);L_ImageProcessGet(a,e,0);b>v?ColorSetTopBufferUP8(e,r,l,p,b,3,m):ColorSetTopBufferDown8(e,r,b,3,m);if(1==g)for(h=0;h<d;h++)L_ImageProcessPut(c,r,h);else{j.value=0;for(h=1;h<g;h++){L_ImageProcessGet(a,f,h);d=j.value;e=0;for(ColorWidthDownUpHeightBilinear8(f,r,k,u,t,l,p,o,b,v,w,j,3,h,m,n);d<=w.value;d++)L_ImageProcessPut(c,
u,d,e),e+=y;d=r;r=k;k=d}}}function ColorWidthDownUpHeightBilinear8(a,c,b,d,f,e,h,g,j,k,m,n,l,o,p,r){m.value=L_ParseInt(r[o]);j>k?ColorDownSampleUP8(a,b,e,h,j,l,p):ColorDownSampleBottom8(a,b,j,l,p);ColorInterpolateHeight8(d,c,b,g,j,l,n.value,m.value,f);n.value=m.value+1}
function ColorInterpolateHeight8(a,c,b,d,f,e,h,g,j){var k,m,n,l,o,p,r,q,s,u,w;for(k=o=l=0;k<f;k++){s=c[l]-b[o];u=c[l+1]-b[o+1];w=c[l+2]-b[o+2];n=k*e;for(m=h;m<=g;m++)q=s?b[o]+(d[m]*s>>10):b[o],p=u?b[o+1]+(d[m]*u>>10):b[o+1],r=w?b[o+2]+(d[m]*w>>10):b[o+2],a[n]=q,a[n+1]=p,a[n+2]=r,n+=j;l+=e;o+=e}}
function ColorDownSampleBottom8(a,c,b,d,f){var e=L_AllocateUint32Array(3),h,g,j=null,k,m,n;for(h=n=j=g=0;h<b;h++){k=f[h];L_MEMSET(e,0,3);for(m=g;m<=k;m++)e[2]+=a[n+2],e[1]+=a[n+1],e[0]+=a[n],n+=d;g=k-g+1;c[j+2]=(e[2]<<10)/g+512>>10;c[j+1]=(e[1]<<10)/g+512>>10;c[j]=(e[0]<<10)/g+512>>10;j+=d;g=m}}
function ColorDownSampleUP8(a,c,b,d,f,e,h){var g=L_AllocateUint32Array(3),j,k,m=null,n,l=!1,o,p;for(j=p=m=k=0;j<f;){n=h[j];L_MEMSET(g,0,3);for(o=k;o<=n;o++)o==k?d[j]&&(l=!0):l=!1,d[j]&&l?(g[2]+=a[p+2]*d[j],g[1]+=a[p+1]*d[j],g[0]+=a[p]*d[j]):(g[2]+=a[p+2]*b[o],g[1]+=a[p+1]*b[o],g[0]+=a[p]*b[o]),p+=e;c[m+2]=g[2]+512>>10;c[m+1]=g[1]+512>>10;c[m]=g[0]+512>>10;m+=e;j++<f&&(d[j]?(k=n,p-=e):k=n+1)}}
function ColorSetTopBufferDown8(a,c,b,d,f){var e=L_AllocateUint32Array(3),h,g,j=null,k=null,m,n;for(h=k=j=g=0;h<b;h++){m=f[h];L_MEMSET(e,0,3);for(n=g;n<=m;n++)e[2]+=a[k+2],e[1]+=a[k+1],e[0]+=a[k],k+=d;g=m-g+1;c[j+2]=(e[2]<<10)/g+512>>10;c[j+1]=(e[1]<<10)/g+512>>10;c[j]=(e[0]<<10)/g+512>>10;j+=d;g=n}}
function ColorSetTopBufferUP8(a,c,b,d,f,e,h){var g=L_AllocateUint32Array(3),j,k,m=null,n=null,l,o=!1,p;for(j=m=n=k=0;j<f;){l=h[j];L_MEMSET(g,0,3);for(p=k;p<=l;p++)p==k?d[j]&&(o=!0):o=!1,d[j]&&o?(g[2]+=a[m+2]*d[j],g[1]+=a[m+1]*d[j],g[0]+=a[m]*d[j]):(g[2]+=a[m+2]*b[p],g[1]+=a[m+1]*b[p],g[0]+=a[m]*b[p]),m+=e;c[n+2]=g[2]+512>>10;c[n+1]=g[1]+512>>10;c[n]=g[0]+512>>10;n+=e;j++<f&&(d[j]?(k=l,m-=e):k=l+1)}}
function DownHieghtUpWidth(a,c,b,d){var f=null,e,h,g,j,k,m=null,n=null,l=null,o=null,p=null,r,q,s,u=null,w=null,v=null,t,y,z=!0,f=L_AllocateUint8Array(3*a.width+12);h=a.height;e=a.width;y=L_ParseInt(h/2);q=d>y?d/h:h/d;1==e?(s=1,t=0):(s=(b-1)/(e-1),t=1);k=3*c.width;u=L_AllocateUint8Array(k);k=e;t||k++;m=Array(k);n=L_AllocateUint32Array(d);l=L_AllocateUint32Array(b);d>y&&(o=L_AllocateUint32Array(h));k=d;p=L_AllocateUint32Array(k);L_MEMSET(p,0,k);k=3*c.width;w=L_AllocateUint8Array(k);k=3*b;v=L_AllocateUint32Array(k);
g=0;for(j=1;j<e;j++)g+=s,m[j]=g;m[0]=0;m[t?e-1:1]=b-1;SetVerticalBuffers(d,h,y,n,o,p,q);SetXRatioBuffers(l,e,s,m);h-=1;r=q=0;for(s=j=-1;j<h;){j=n[q];L_MEMSET(v,0,k);for(g=r;g<=j;g++)g==r?p[q]&&(z=!0):z=!1,s!=r&&L_ImageProcessGet(a,f,g),s=j,WidthColorBilinearInterpolate8(f,w,o,p,j,l,d,e,y,q,g,3,t,z,v,m);g=j-r+1;ColorCalculateAverage8(u,g,b,d,y,3,v);L_ImageProcessPut(c,u,q);r=j+1;d>y&&q+1<d&&p[q+1]&&(r=j);q++}}
function ColorCalculateAverage8(a,c,b,d,f,e,h){var g,j=0;g=0;if(d>f)for(d=0;d<b;d++)a[j+2]=h[g+2]+512>>10,a[j+1]=h[g+1]+512>>10,a[j]=h[g]+512>>10,j+=e,g+=e;else for(d=0;d<b;d++)a[j+2]=1024*h[g+2]/c+512>>10,a[j+1]=1024*h[g+1]/c+512>>10,a[j]=1024*h[g]/c+512>>10,j+=e,g+=e}
function WidthColorBilinearInterpolate8(a,c,b,d,f,e,h,g,j,k,m,n,l,o,p,r){var q,s,u,w=L_AllocateUint8Array(2),v=L_AllocateUint8Array(2),t=L_AllocateUint8Array(2),y,z,x,D,A=null,B=null,C=null,E,C=A=q=0;E=h>j;B=0;for(x=l;x<g;x++){D=L_ParseInt(r[x]);t[0]=a[A];v[0]=a[A+1];w[0]=a[A+2];l?A+=n:D=L_ParseInt(r[x+1]);t[1]=a[A];v[1]=a[A+1];w[1]=a[A+2];h=t[1]-t[0];j=v[1]-v[0];y=w[1]-w[0];for(z=q;z<=D;z++)E?d[k]&&o?(p[C]+=c[B]*d[k],p[C+1]+=c[B+1]*d[k],p[C+2]+=c[B+2]*d[k],B+=n):(u=h?t[0]+(e[z]*h>>10):t[0],q=j?v[0]+
(e[z]*j>>10):v[0],s=y?w[0]+(e[z]*y>>10):w[0],m==f&&d[k+1]&&(c[B+2]=s,c[B+1]=q,c[B]=u,B+=n),p[C]+=u*b[m],p[C+1]+=q*b[m],p[C+2]+=s*b[m]):(u=h?t[0]+(e[z]*h>>10):t[0],q=j?v[0]+(e[z]*j>>10):v[0],s=y?w[0]+(e[z]*y>>10):w[0],p[C]+=u,p[C+1]+=q,p[C+2]+=s),C+=n;q=z}}function SetXRatioBuffers(a,c,b,d){var f,e,h,g=0,j;e=0;for(f=1;f<c;f++){h=d[f];j=L_ParseInt(d[f]);for(e=g-e;g<=j;g++)a[g]=L_ParseInt(1024*e/b),e+=1;e=h}}
function DownSampleBitmap(a,c,b,d){var f=null,e,h,g,j=null,k=null,m=null,n=null,l=null,o=null,p,r,q=null,s,u;h=a.height;e=a.width;s=L_ParseInt(h/2);u=L_ParseInt(e/2);r=3*a.width;d>s?(f=d/h,j=L_ParseInt(1/f+2)):(f=h/d,j=L_ParseInt(f)+2);p=b>u?b/e:e/b;g=3*a.width*j;q=L_AllocateUint8Array(g);j=L_AllocateUint32Array(b);k=L_AllocateUint32Array(d);b>u&&(m=L_AllocateUint32Array(e));d>s&&(n=L_AllocateUint32Array(h));g=b;l=L_AllocateUint32Array(g);L_MEMSET(l,0,g);g=d;o=L_AllocateUint32Array(g);L_MEMSET(o,
0,g);SetHorizentalBuffers(b,e,u,j,m,l,p);SetVerticalBuffers(d,h,s,k,n,o,f);f=L_AllocateUint8Array(3*c.width+12);b!=e?b>u?UppererDownSample(q,f,c,a,r,8,b,d,h,e,u,s,3,j,k,m,n,l,o):BottomDownSample(q,f,c,a,r,8,b,d,h,e,u,s,3,j,k,m,n,l,o):d>s?UppererDownSample(q,f,c,a,r,8,b,d,h,e,u,s,3,j,k,m,n,l,o):BottomDownSample(q,f,c,a,r,8,b,d,h,e,u,s,3,j,k,m,n,l,o)}
function BottomDownSample(a,c,b,d,f,e,h,g,j,k,m,n,l,o,p,r,q,s,u){var w,v,t,y,z;v=j-1;e=t=0;w=-1;z=l*k;z+=f-z;for(y=0;w<v;){w=p[t];for(k=e;k<=w;k++)L_ImageProcessGet(d,a,k,y),y+=f;y=0;3==l&&BottomColorCalculateAverage8(c,a,z,h,g,j,m,n,e,w,l,o,r,q,s,u,t);L_ImageProcessPut(b,c,t);t++;t<g&&(e=u[t]?w:w+1)}}
function BottomColorCalculateAverage8(a,c,b,d,f,e,h,g,j,k,m,n,l,o,p,r,q){var s,u,w,v=null,t,y,z,x=null,D=null,A=null,B,C=0,E;y=0;if(d<=h&&(f<=g||f==e)){A=0;f=k-j+1;for(t=0;t<d;t++){E=y;z=n[t];x=s=y*m;s=u=w=0;y=(z-E+1)*f;for(C=j;C<=k;C++){v=x;for(B=E;B<=z;B++)s+=c[v+2],u+=c[v+1],w+=c[v],v+=m;x+=b}a[A+2]=L_ParseInt(1024*s/y+512>>10);a[A+1]=L_ParseInt(1024*u/y+512>>10);a[A]=L_ParseInt(1024*w/y+512>>10);A+=m;y=z+1}}else if(f<=g){A=0;y=k-j+1;for(t=0;t<d;t++){x=s=t*m;s=u=w=0;for(C=j;C<=k;C++)v=x,s+=c[v+
2],u+=c[v+1],w+=c[v],x+=b;a[A+2]=L_ParseInt(1024*s/y+512>>10);a[A+1]=L_ParseInt(1024*u/y+512>>10);a[A]=L_ParseInt(1024*w/y+512>>10);A+=m}}else{for(t=0;t<d;t++){E=y;z=n[t];x=s=y*m;D=t*m;y=z-E+1;for(C=j;C<=k;C++){v=x;A=D;s=u=w=0;for(B=E;B<=z;B++)s+=c[v+2],u+=c[v+1],w+=c[v],v+=m;c[A+2]=L_ParseInt(1024*s/y+512>>10);c[A+1]=L_ParseInt(1024*u/y+512>>10);c[A]=L_ParseInt(1024*w/y+512>>10);x+=b;D+=b}y=z+1}UpperColorCalculateAverage8(a,c,b,d,f,e,d,h,g,j,k,m,n,l,o,p,r,q)}}
function UppererDownSample(a,c,b,d,f,e,h,g,j,k,m,n,l,o,p,r,q,s,u){var w,v,t,y,z,x;v=j-1;e=t=0;w=-1;x=l*k;x+=f-x;for(z=0;w<v;){w=p[t];for(y=e;y<=w;y++)L_ImageProcessGet(d,a,y,z),z+=f;z=0;3==l&&UpperColorCalculateAverage8(c,a,x,h,g,j,k,m,n,e,w,l,o,r,q,s,u,t);L_ImageProcessPut(b,c,t);t++;t<g&&(e=u[t]?w:w+1)}}
function UpperColorCalculateAverage8(a,c,b,d,f,e,h,g,j,k,m,n,l,o,p,r,q,s){var u,w,v,t=null,y,z,x,D=x=null,A=null,B,C=0,E;y=0;if(d>g&&d!=h)for(h=0;h<d;h++){E=y;z=l[h];x=y*n;D=h*n;for(C=k;C<=m;C++){t=x;A=D;u=w=v=0;B=E;r[h]&&(u+=c[t+2]*r[h],w+=c[t+1]*r[h],v+=c[t]*r[h],t+=n,B++);for(;B<=z;B++)u+=c[t+2]*o[B],w+=c[t+1]*o[B],v+=c[t]*o[B],t+=n;c[A+2]=L_ParseInt(u+512>>10);c[A+1]=L_ParseInt(w+512>>10);c[A]=L_ParseInt(v+512>>10);x+=b;D+=b}h+1<d&&(y=r[h+1]?z:z+1)}if(f>j)for(h=A=0;h<d;h++){x=h*n;u=w=v=0;f=k;
q[s]&&(u+=c[x+2]*q[s],w+=c[x+1]*q[s],v+=c[x]*q[s],x+=b,f++);for(C=f;C<=m;C++)u+=c[x+2]*p[C],w+=c[x+1]*p[C],v+=c[x]*p[C],x+=b;a[A+2]=L_ParseInt(u+512>>10);a[A+1]=L_ParseInt(w+512>>10);a[A]=L_ParseInt(v+512>>10);A+=n}else BottomColorCalculateAverage8(a,c,b,d,f,e,g,j,k,m,n,l,o,p,r,q,s)}
function SetHorizentalBuffers(a,c,b,d,f,e,h){var g,j,k,m;if(a>b)for(b=j=g=m=k=0;b<c;)g?(e[m]=L_ParseInt(1024*g),j=k+=g,g=0,b++):(k+=h,1<=k?(d[m]=b,g=1-j,f[b]=L_ParseInt(1024*g),k=L_ParseInt(1E4*k),1E4!=k?g=h-g:(g=0,b++),k=0,m++):(f[b]=L_ParseInt(1024*h),j=k,b++));else{f=a-1;for(b=k=0;b<f;b++)k+=h,d[b]=L_ParseInt(k-1)}d[a-1]=c-1}
function SetVerticalBuffers(a,c,b,d,f,e,h){var g,j,k,m;if(a>b)for(m=j=g=k=b=0;m<c;)g?(e[k]=L_ParseInt(1024*g),j=b+=g,g=0,m++):(b+=h,1<=b?(d[k]=m,g=1-j,f[m]=L_ParseInt(1024*g),b=L_ParseInt(1E4*b),1E4!=b?g=h-g:(g=0,m++),b=0,k++):(f[m]=L_ParseInt(1024*h),j=b,m++));else{f=a-1;for(e=b=0;e<f;e++)b+=h,d[e]=L_ParseInt(b-1)}d[a-1]=c-1}
function UpSampleBitmap(a,c,b,d){var f=null,e=null,h,g,j,k,m=null,n=null,e=null,l,o=k=null,p=null,r,q,s={},u,w,v,t=e=null,y=null,z={},f=L_AllocateUint8Array(3*a.width+12),e=L_AllocateUint8Array(3*a.width+12);g=a.height;h=a.width;w=3*b;v=3*c.width;w+=v-w;r=1==g?1:(d-1)/(g-1);q=1==h?1:(b-1)/(h-1);m=L_ParseInt(r+1);u=1<h?1:0;k=3*c.width*m;t=L_AllocateUint8Array(k);k=3*c.width;m=L_AllocateUint8Array(k);n=L_AllocateUint8Array(k);k=h;u||k++;k=Array(k);o=Array(g);p=L_AllocateUint32Array(b);y=L_AllocateUint32Array(d);
l=0;for(j=1;j<h;j++)l+=q,k[j]=l;k[0]=0;k[u?h-1:1]=b-1;j=0;for(b=1;b<g;b++)j+=r,o[b]=j;o[0]=0;o[g-1]=d-1;SetYRatioBuffers(y,g,r,o);L_ImageProcessGet(a,e,0);SetTopAndTopXRatioBuffers8(e,m,p,h,3,u,q,k);if(1==g)for(b=0;b<d;b++)L_ImageProcessPut(c,m,b);else{s.value=0;for(b=1;b<g;b++){L_ImageProcessGet(a,f,b);d=s.value;ColorBilinearInterpolate8(f,m,n,t,w,p,y,z,s,h,3,b,u,k,o);e=0;for(j=d;j<=z.value;j++)L_ImageProcessPut(c,t,j,e),e+=v;e=m;m=n;n=e}}}
function ColorBilinearInterpolate8(a,c,b,d,f,e,h,g,j,k,m,n,l,o,p){var r=L_AllocateUint8Array(2),q=L_AllocateUint8Array(2),s=L_AllocateUint8Array(2),u,w,v,t=0,y=u=null,z,x;x=null;var D,A;w=null;var B;g.value=L_ParseInt(p[n]);p=x=0;for(z=l;z<k;z++){D=L_ParseInt(o[z]);s[0]=a[p];q[0]=a[p+1];r[0]=a[p+2];l?p+=m:D=L_ParseInt(o[z+1]);s[1]=a[p];q[1]=a[p+1];r[1]=a[p+2];u=s[1]-s[0];w=q[1]-q[0];v=r[1]-r[0];y=A=x*m;for(n=x;n<=D;n++)b[y]=u?L_ParseInt(s[0]+(e[n]*u>>10)):L_ParseInt(s[0]),b[y+1]=w?L_ParseInt(q[0]+
(e[n]*w>>10)):L_ParseInt(q[0]),b[y+2]=v?L_ParseInt(r[0]+(e[n]*v>>10)):L_ParseInt(r[0]),y+=m;y=u=w=A;for(n=x;n<=D;n++){B=c[u]-b[y];v=c[u+1]-b[y+1];A=c[u+2]-b[y+2];x=w;for(t=j.value;t<=g.value;t++)d[x]=B?L_ParseInt(b[y]+(h[t]*B>>10)):L_ParseInt(b[y]),d[x+1]=v?L_ParseInt(b[y+1]+(h[t]*v>>10)):L_ParseInt(b[y+1]),d[x+2]=A?L_ParseInt(b[y+2]+(h[t]*A>>10)):L_ParseInt(b[y+2]),x+=f;w+=m;u+=m;y+=m}x=n}j.value=t}
function SetTopAndTopXRatioBuffers8(a,c,b,d,f,e,h,g){var j=L_AllocateUint8Array(2),k=L_AllocateUint8Array(2),m=L_AllocateUint8Array(2),n,l,o,p,r,q=null,s,u,w;p=0;var v;r=u=0;for(s=e;s<d;s++){w=g[s];v=L_ParseInt(g[s]);m[0]=a[r];k[0]=a[r+1];j[0]=a[r+2];e?r+=f:v=L_ParseInt(g[s+1]);m[1]=a[r];k[1]=a[r+1];j[1]=a[r+2];n=m[1]-m[0];l=k[1]-k[0];o=j[1]-j[0];q=p*f;for(u=p-u;p<=v;p++)b[p]=L_ParseInt(1024*u/h),c[q]=n?L_ParseInt(m[0]+(b[p]*n>>10)):L_ParseInt(m[0]),c[q+1]=l?L_ParseInt(k[0]+(b[p]*l>>10)):L_ParseInt(k[0]),
c[q+2]=o?L_ParseInt(j[0]+(b[p]*o>>10)):L_ParseInt(j[0]),q+=f,u+=1;u=w}}function SetYRatioBuffers(a,c,b,d){var f,e,h=0,g;for(f=1;f<c;f++){e=d[f];g=L_ParseInt(d[f]);for(e=h-e;h<=g;h++)a[h]=L_ParseInt(1024*e/-b),e+=1}}
function SlowSpeedFilters(a,c,b,d,f){var e=null,h=null,g,j,k,m,n=null,l=null,o=g=null,p=null,r=null,q=null,s=null,u=null,w=j=null,v=null,t=null,y=!1,z,x,D;x=1;var A,B,C,E,e=L_AllocateUint8Array(3*a.width+12);null!=c?h=c:(h={},h.data=L_AllocateUint8Array(4*b*d),h.width=b,h.height=d);for(o=0;o<b*d;o++)h.data[4*o+3]=255;j=a.height;g=a.width;v=3*h.width;switch(f){case 11:x=3;break;case 12:x=2;break;case 13:x=1;break;case 14:x=2;break;case 15:x=1.5;break;case 16:x=3}n=b/g;A=d/j;1<=A?z=L_ParseInt(2*x+2):
(z=L_ParseInt(2*(x/A)+3),y=!0);z>j&&(z=j);l=L_AllocateUint8Array(v*z);t=Array(z);for(o=0;o<z;o++)t[o]={};c=b;o=L_AllocateInt32Array(c);r=L_AllocateInt32Array(c);c=d;p=L_AllocateInt32Array(c);q=L_AllocateInt32Array(c);w=L_AllocateInt32Array(c);B=1<=n?L_ParseInt(2*x+2):L_ParseInt(2*(x/n)+2);B>g&&(B=g);s=L_AllocateInt32Array(2*B*b);u=L_AllocateInt32Array(2*z*d);c=v;n=L_AllocateUint8Array(c);D=2*z;B*=2;E=z-1;1>A&&z--;A=z-1;SetPixelsData(b,3,B,g,!1,0,f,x,o,r,null,s,E);SetPixelsData(d,3,D,j,!0,A,f,x,p,
q,w,u,E);g=0;x=z;for(f=0;f<x&&f<j;f++)L_ImageProcessGet(a,e,f),ColorSlowSpeedLineInterpolate8(e,l,g,o,r,s,B,b,3),t[f].pIndex=g,g+=v;y&&(t[E].pIndex=g,L_CopyArrayRange(l,t[0].pIndex,l,t[E].pIndex,c));g=w[0];for(f=v=j=0;f<d;f++){z=w[v];if(z!=g)for(g=x;g<=z;g++){x++;y&&y&&L_CopyArrayRange(l,t[0].pIndex,l,t[E].pIndex,c);for(k=0;k<A;k++)C=k+1,m=t[k].pIndex,t[k].pIndex=t[C].pIndex,t[C].pIndex=m;L_ImageProcessGet(a,e,g);ColorSlowSpeedLineInterpolate8(e,l,t[k].pIndex,o,r,s,B,b,3)}ColorVerticalInterpolate8(l,
t,n,p,q,u,j,f,b,3);L_ImageProcessPut(h,n,f);g=z;j+=D;v++}return h}function ColorSlowSpeedLineInterpolate8(a,c,b,d,f,e,h,g,j){var k,m,n,l,o,p,r,q,s,u;for(k=q=s=0;k<g;k++){l=o=p=0;n=d[k];u=s;for(m=0;m<n;m++)r=e[u],l+=a[r+2]*e[u+1],o+=a[r+1]*e[u+1],p+=a[r]*e[u+1],u+=2;m=f[k];c[b+q+2]=L_ParseInt(Math.max(0,Math.min(255,l/m)));c[b+q+1]=L_ParseInt(Math.max(0,Math.min(255,o/m)));c[b+q+0]=L_ParseInt(Math.max(0,Math.min(255,p/m)));q+=j;s+=h}}
function ColorVerticalInterpolate8(a,c,b,d,f,e,h,g,j,k){var m,n,l,o,p,r,q,s;q=0;f=f[g];m=d[g];for(d=0;d<j;d++){n=l=o=0;p=d*k;s=h;for(g=0;g<m;g++)r=c[e[s]].pIndex+p,n+=a[r+2]*e[s+1],l+=a[r+1]*e[s+1],o+=a[r]*e[s+1],s+=2;b[q+2]=L_ParseInt(Math.max(0,Math.min(255,n/f)));b[q+1]=L_ParseInt(Math.max(0,Math.min(255,l/f)));b[q]=L_ParseInt(Math.max(0,Math.min(255,o/f)));q+=k}}
function MiddleSpeedFilters(a,c,b,d,f){var e=null,h=null,g,j,k,m,n=null,l=null,o=g=null,p=null,r=null,q=null,s=null,u=null,w=j=null,v=null,t=null,y=!1,z,x,D;x=1;var A,B,C,E,e=L_AllocateUint8Array(3*a.width+12);null!=c?h=c:(h={},h.data=L_AllocateUint8Array(4*b*d),h.width=b,h.height=d);for(o=0;o<b*d;o++)h.data[4*o+3]=255;j=a.height;g=a.width;v=3*h.width;switch(f){case 5:case 6:x=1;break;case 7:case 8:x=1.5;break;case 9:x=2;break;case 10:x=0.5}n=b/g;A=d/j;1<=A?z=L_ParseInt(2*x+2):(z=L_ParseInt(2*(x/
A)+3),y=!0);z>j&&(z=j);l=L_AllocateUint8Array(v*z);t=Array(z);for(o=0;o<z;o++)t[o]={};c=b;o=L_AllocateInt32Array(c);r=L_AllocateInt32Array(c);c=d;p=L_AllocateInt32Array(c);q=L_AllocateInt32Array(c);w=L_AllocateInt32Array(c);B=1<=n?L_ParseInt(2*x+2):L_ParseInt(2*(x/n)+2);B>g&&(B=g);s=L_AllocateInt32Array(2*B*b);u=L_AllocateInt32Array(2*z*d);c=v;n=L_AllocateUint8Array(c);D=2*z;B*=2;E=z-1;1>A&&z--;A=z-1;SetPixelsData(b,3,B,g,!1,0,f,x,o,r,null,s,E);SetPixelsData(d,3,D,j,!0,A,f,x,p,q,w,u,E);g=0;x=z;for(f=
0;f<x&&f<j;f++)L_ImageProcessGet(a,e,f),ColorMiddeSpeedLineInterpolate8(e,l,g,o,r,s,B,b,3),t[f].pIndex=g,g+=v;y&&(t[E].pIndex=g,L_CopyArrayRange(l,t[0].pIndex,l,t[E].pIndex,c));g=w[0];for(f=v=j=0;f<d;f++){z=w[v];if(z!=g)for(g=x;g<=z;g++){x++;y&&y&&L_CopyArrayRange(l,t[0].pIndex,l,t[E].pIndex,c);for(k=0;k<A;k++)C=k+1,m=t[k].pIndex,t[k].pIndex=t[C].pIndex,t[C].pIndex=m;L_ImageProcessGet(a,e,g);ColorMiddeSpeedLineInterpolate8(e,l,t[k].pIndex,o,r,s,B,b,3)}ColorVerticalMiddeSpeedInterpolate8(l,t,n,p,q,
u,j,f,b,3);L_ImageProcessPut(h,n,f);g=z;j+=D;v++}return h}function ColorVerticalMiddeSpeedInterpolate8(a,c,b,d,f,e,h,g,j,k){var m,n,l,o,p,r,q,s;q=0;f=f[g];m=d[g];for(d=0;d<j;d++){n=l=o=0;p=d*k;s=h;for(g=0;g<m;g++)r=c[e[s]].pIndex+p,n+=a[r+2]*e[s+1],l+=a[r+1]*e[s+1],o+=a[r]*e[s+1],s+=2;b[q+2]=L_ParseInt(n/f);b[q+1]=L_ParseInt(l/f);b[q]=L_ParseInt(o/f);q+=k}}
function ColorMiddeSpeedLineInterpolate8(a,c,b,d,f,e,h,g,j){var k,m,n,l,o,p,r,q,s,u;for(k=q=s=0;k<g;k++){l=o=p=0;n=d[k];u=s;for(m=0;m<n;m++)r=e[u],l+=a[r+2]*e[u+1],o+=a[r+1]*e[u+1],p+=a[r]*e[u+1],u+=2;m=f[k];c[b+q+2]=L_ParseInt(l/m);c[b+q+1]=L_ParseInt(o/m);c[b+q+0]=L_ParseInt(p/m);q+=j;s+=h}}function TriangleWeight(a){0>a&&(a=-a);return 1>a?1-a:0}function HermiteWeight(a){0>a&&(a=-a);return 1>a?(2*a-3)*a*a+1:0}function BellWeight(a){0>a&&(a=-a);return 0.5>a?0.75-a*a:1.5>a?(a-=1.5,0.5*a*a):0}
function QuadraticBSplineWeight(a){0>a&&(a=-a);return 0.5>=a?-a*a+0.75:1.5>=a?0.5*a*a-1.5*a+1.125:0}function CubicBSpline(a){var c,b,d;c=0<a+2?a+2:0;b=0<a+1?a+1:0;d=0<a?a:0;a=0<a-1?a-1:0;return(c*c*c-4*b*b*b+6*d*d*d-4*a*a*a)/6}function BoxFilter(a){0>a&&(a=-a);return 0.5>=a?1:0}function Sinc(a){return 0!=a?(a*=3.142,Math.sin(a)/a):1}function LanczosWeight(a){0>a&&(a=-a);return 3>a?Sinc(a)*Sinc(a/3):0}
function MitchellWeight(a){var c;0>a&&(a=-a);c=a*a;return 1>a?(7*a*c+-12*c+5.333333)/6:2>a?(-2.3333333*a*c+12*c+-20*a+10.666666)/6:0}function CosineWeight(a){return-1<=a&&1>=a?(Math.cos(3.142*a)+1)/2:0}function CatmullRomWeight(a){var c;0>a&&(a=-a);c=a*a;return 1>=a?1.5*c*a-2.5*c+1:2>=a?-0.5*c*a+2.5*c-4*a+2:0}function QuadraticWeight(a){0>a&&(a=-a);return 0.5>=a?-2*a*a+1:1.5>=a?a*a-2.5*a+1.5:0}
function CubicConvolutionWeight(a){var c;0>a&&(a=-a);c=a*a;return 1>=a?1.3333333*c*a-2.3333333*c+1:2>=a?-0.5833333333*c*a+3*c-4.916666666666*a+2.5:3>=a?0.0833333333*c*a-0.666666666*c+1.75*a-1.5:0}
function SetPixelsData(a,c,b,d,f,e,h,g,j,k,m,n,l){var o,p,r,q,s,u,w,v,t,y=0;w=0;v=LanczosWeight;r=a/d;t=1<=r?g:g/r;g=0;switch(h){case 5:v=TriangleWeight;break;case 6:v=HermiteWeight;break;case 7:v=BellWeight;break;case 8:v=QuadraticBSplineWeight;break;case 9:v=CubicBSpline;break;case 10:v=BoxFilter;break;case 11:v=LanczosWeight;break;case 12:v=MitchellWeight;break;case 13:v=CosineWeight;break;case 14:v=CatmullRomWeight;break;case 15:v=QuadraticWeight;break;case 16:v=CubicConvolutionWeight}for(h=0;h<
a;h++){j[h]=0;k[h]=0;q=(h+0.5)/r;u=w;o=Math.floor(q-t);s=Math.ceil(q+t);0>o&&(o=0);s>=d&&(s=d-1);f&&(s>e&&s<d&&(g+=s-e,e=s),m[y]=s);for(;o<=s;o++)p=1<r?L_ParseInt(1024*v(q-o-0.5)):L_ParseInt(1024*v((q-o-0.5)*r)),0!=p&&(f?(n[u]=o-g,-1==n[u]&&(n[u]=l)):n[u]=o*c,n[u+1]=p,k[h]+=p,j[h]++,u+=2);w+=b;y++}}
Leadtools_ImageProcessing_Core_Despeckle=function(a){var c=a.imageData;a.useProgress?(_progressData={start:0,end:100},_progressData.resultImageHeight=c.height):_progressData=null;L_DespeckleBitmap(c);_callback&&_callback({status:"Completed",imageData:c})};function L_DespeckleBitmap(a){L_DespeckleColorBitmap(a)}
function L_DespeckleColorBitmap(a){var c,b,d=null,f=null,e=null,h=null,g;g=3*a.width+12;h=L_AllocateUint8Array(g);d=L_AllocateUint8Array(g);f=L_AllocateUint8Array(g);e=L_AllocateUint8Array(g);for(c=0;c<a.height;c++)0==c&&(GetLine(a,d,a.width,0,3),L_CopyArray(d,f,g)),GetLine(a,e,a.width,Math.min(c+1,a.height-1),3),DespeckleLine8(a.width,h,d,f,e,3,6),L_ImageProcessPut(a,h,c),b=d,d=f,f=e,e=b}
function DespeckleLine8(a,c,b,d,f,e,h){var g,j={},k={},m={},n={},l={},o={},p,r,q,s,u;for(g=0;g<e;g++){s=q=r=p=g;for(u=a;u--;)j.value=b[r],k.value=b[r+e],m.value=b[r+h],n.value=d[q],l.value=d[q+e],o.value=d[q+h],mnmx6(j,k,m,n,l,o),j.value=f[s],mnmx5(j,k,m,n,l),j.value=f[s+e],mnmx4(j,k,m,n),j.value=f[s+h],mnmx3(j,k,m),c[p]=128<Math.abs(d[q+e]-k.value)?k.value:d[q+e],p+=e,r+=e,q+=e,s+=e}}function mnmx3(a,c,b){mx3(a,c,b);s2(a,c)}function mnmx4(a,c,b,d){s2(a,c);s2(b,d);s2(a,b);s2(c,d)}
function mnmx5(a,c,b,d,f){s2(a,c);s2(b,d);mn3(a,b,f);mx3(c,d,f)}function mnmx6(a,c,b,d,f,e){s2(a,d);s2(c,f);s2(b,e);mn3(a,c,b);mx3(d,f,e)}function s2(a,c){var b;if(0>(b=c.value-a.value))a.value+=b,c.value-=b}function mn3(a,c,b){s2(a,c);s2(a,b)}function mx3(a,c,b){s2(c,b);s2(a,b)}function GetLine(a,c,b,d,f){L_ImageProcessGet(a,c,d,f);for(a=0;a<f;a++)c[a]=c[a+f];for(a=0;a<f;a++)c[a+f+b*f]=c[a+b*f]}function L_CopyArray(a,c,b){for(var d=0;d<b;d++)null!=a[d]&&(c[d]=a[d])}
function L_CopyArrayRange(a,c,b,d,f){for(var e=0;e<f;e++)null!=a[e+c]&&(b[e+d]=a[e+c])}
Leadtools_ImageProcessing_Core_MinFilter=function(a){var c=a.imageData;a.useProgress?(_progressData={start:0,end:100},_progressData.resultImageHeight=c.height):_progressData=null;var a=a.dimension,b,d,f,e,h,g,j,k=null,m=null,n,l,o,p={},r;if(!a)throw Error("ERROR INV PARAMETER");r=c.width;p.left=0;p.right=c.width;p.top=0;p.bottom=c.height;n=L_AllocateUint32Array(256);j=a*a;h=a-1>>1;g=(a>>1)+1;d=3*c.width+12;k=L_AllocateUint8Array(d);m=Array(a);d=3*c.width;for(b=0;b<a;b++)m[b]=L_AllocateUint8Array(d);
o=c.height-1;e=p.top-h;f=-h;l=0>e?0:e;d=p.top;for(b=0;d<p.bottom;)L_ImageProcessGet(c,m[b],l),b++,b==a&&(b=0),f++,0<=e&&e<o&&l++,e++,f>=g&&(L_MEMSET(k,0,3*c.width),LineMin8(m,k,n,h,g,a,j,3,p,r),L_ImageProcessPut(c,k,d),d++);_callback&&_callback({status:"Completed",imageData:c})};
function LineMin8(a,c,b,d,f,e,h,g,j,k){var m,n,l,o,p,r,q,s,u,w,v,t,y;w=(f-(e+1)%2)*g;v=(d+(e+1)%2)*g;for(o=0;o<g;o++){y=!1;GetHistogram8(a,o+j.left*g,b,d,f,e,h,k,o,g);p=GetMin8(b);c[o+j.left*g]=Math.min(p,255);m=j.right*g-(g-o);n=k*g-(g-o);for(l=o+g+j.left*g;l<=m;l+=g){q=l-w;q<o&&(q=o);s=l+v;s>n&&(s=n);r=p;for(u=0;u<e;u++)t=a[u],b[t[q]]--,t[q]==p&&(y=!0),b[t[s]]++,t[s]<r&&(r=t[s]);p=GetMinFast8(b,p,r,y);c[l]=Math.min(p,255)}}}
Leadtools_ImageProcessing_Core_MaxFilter=function(a){var c=a.imageData;a.useProgress?(_progressData={start:0,end:100},_progressData.resultImageHeight=c.height):_progressData=null;var a=a.dimension,b,d,f,e,h,g,j,k=null,m=null,n,l,o,p={},r;if(!a)throw Error("ERROR INV PARAMETER");r=c.width;p.left=0;p.right=c.width;p.top=0;p.bottom=c.height;n=L_AllocateUint32Array(256);j=a*a;h=a-1>>1;g=(a>>1)+1;d=3*c.width+12;k=L_AllocateUint8Array(d);m=Array(a);d=3*c.width;for(b=0;b<a;b++)m[b]=L_AllocateUint8Array(d);
o=c.height-1;e=p.top-h;f=-h;l=0>e?0:e;d=p.top;for(b=0;d<p.bottom;)L_ImageProcessGet(c,m[b],l),b++,b==a&&(b=0),f++,0<=e&&e<o&&l++,e++,f>=g&&(L_MEMSET(k,0,3*c.width),LineMax8(m,k,n,h,g,a,j,3,p,r),L_ImageProcessPut(c,k,d),d++);_callback&&_callback({status:"Completed",imageData:c})};
function LineMax8(a,c,b,d,f,e,h,g,j,k){var m,n,l,o,p,r,q,s,u,w,v,t,y;w=(f-(e+1)%2)*g;v=(d+(e+1)%2)*g;for(o=0;o<g;o++){y=!1;GetHistogram8(a,o+j.left*g,b,d,f,e,h,k,o,g);p=GetMax8(b);c[o+j.left*g]=Math.min(p,255);m=j.right*g-(g-o);n=k*g-(g-o);for(l=o+g+j.left*g;l<=m;l+=g){q=l-w;q<o&&(q=o);s=l+v;s>n&&(s=n);r=p;for(u=0;u<e;u++)t=a[u],b[t[q]]--,t[q]==p&&(y=!0),b[t[s]]++,t[s]>r&&(r=t[s]);p=y&&r==p?GetMaxFast8(b,p):r;c[l]=Math.min(p,255)}}}
function GetHistogram8(a,c,b,d,f,e,h,g,j,k){var m,n;L_MEMSET(b,0,256);f=c+f*k;n=g*k-(k-j);for(g=h=0;h<e;h++)for(m=c-d*k;m<f;m+=k,g++)m<=j?b[a[h][j]]++:m>n?b[a[h][n]]++:b[a[h][m]]++}function L_MEMSET(a,c,b){for(var d=0;d<b;d++)a[d]=c}function RemapBitmapIntensity(a,c,b){if(3<b)throw Error("ERROR_INV_PARAMETER");if(null==c)throw Error("ERROR_INV_PARAMETER");RemapBitmapIntensity_Pixel(a,c,b)}
function RemapBitmapIntensity_Pixel(a,c,b){var d=null,f=null,e,h,g,j,k;zScanSize=3*a.width+12;d=L_AllocateUint8Array(zScanSize);f=Array(2);f[0]=0;j=f[1]=a.width;k=a.height;for(h=0;h<k;h++){L_ImageProcessGet(a,d,h);for(g=0;2>g;g+=2)if(0==b)for(i=0;i<3*j;i+=3)d[i]=Math.min(c[d[i]],255),d[i+1]=Math.min(c[d[i+1]],255),d[i+2]=Math.min(c[d[i+2]],255);else for(e=f[g];e<3*f[g+1];e+=3){if(0==b||1==b)d[e]=Math.min(c[d[e]],255);if(0==b||2==b)d[e+1]=Math.min(c[d[e+1]],255);if(0==b||3==b)d[e+2]=Math.min(c[d[e+
2]],255)}L_ImageProcessPut(a,d,h)}}function GetMax8(a){for(var c=255;0>=a[c];)c--;return c}function GetMin8(a){for(var c=0;0>=a[c];)c++;return c}function GetMaxFast8(a,c){for(var b=c;0>=a[b];)b--;return b}function GetMinFast8(a,c,b,d){var f=c;if(d&&b==c){for(;0>=a[f];)f++;return f}return b}function L_GetWidth(a){if("TOP_LEFT"==_perspective)return a.width;if("LEFT_TOP"==_perspective)return a.height}
function L_GetHeight(a){if("TOP_LEFT"==_perspective)return a.height;if("LEFT_TOP"==_perspective)return a.width}function L_ImageProcessGet(a,c,b,d){d="undefined"===typeof d?0:d;if("TOP_LEFT"==_perspective)for(var f=4*a.width*(b+1),b=4*a.width*b;b<f;b+=4)c[d]=a.data[b+2],c[1+d]=a.data[b+1],c[2+d]=a.data[b],d+=3;else if("LEFT_TOP"==_perspective)for(var f=4*a.width,e=4*b,b=0;b<a.height;b+=1)c[d]=a.data[b*f+e+2],c[1+d]=a.data[b*f+e+1],c[2+d]=a.data[b*f+e],d+=3}
function L_ImageProcessPut(a,c,b){var d=0;if("TOP_LEFT"==_perspective)for(var f=4*a.width*(b+1),b=4*a.width*b;b<f;b+=4)a.data[b+2]=c[d],a.data[b+1]=c[d+1],a.data[b]=c[d+2],d+=3;else if("LEFT_TOP"==_perspective)for(var f=4*a.width,e=4*b,b=0;b<a.height;b+=1)a.data[b*f+e+2]=c[d],a.data[b*f+e+1]=c[d+1],a.data[b*f+e]=c[d+2],d+=3;null!=_progressData&&increaseProgress()}
function L_ImageProcessPutNoInc(a,c,b){var d=0;if("TOP_LEFT"==_perspective)for(var f=4*a.width*(b+1),b=4*a.width*b;b<f;b+=4)a.data[b+2]=c[d],a.data[b+1]=c[d+1],a.data[b]=c[d+2],d+=3;else if("LEFT_TOP"==_perspective)for(var f=4*a.width,e=4*b,b=0;b<a.height;b+=1)a.data[b*f+e+2]=c[d],a.data[b*f+e+1]=c[d+1],a.data[b*f+e]=c[d+2],d+=3}function L_AllocateUint32Array(a){return array=void 0!=self.Uint32Array?new Uint32Array(a):Array(a)}
function L_AllocateUint32ArrayInit(a){if(void 0!=self.Uint32Array)array=new Uint32Array(a);else{array=Array(a);for(var c=0;c<a;c++)array[c]=0}return array}function L_AllocateInt32Array(a){return array=void 0!=self.Int32Array?new Int32Array(a):Array(a)}function L_AllocateInt32Array(a){return array=void 0!=self.Int32Array?new Int32Array(a):Array(a)}
function L_AllocateInt32ArrayInit(a){if(void 0!=self.Int32Array)array=new Int32Array(a);else{array=Array(a);for(var c=0;c<a;c++)array[c]=0}return array}function L_AllocateUint8Array(a){return array=void 0!=self.Uint8Array?new Uint8Array(a):Array(a)}function L_AllocateUint8ArrayInit(a){if(void 0!=self.Uint8Array)array=new Uint8Array(a);else{array=Array(a);for(var c=0;c<a;c++)array[c]=0}return array}
function L_AllocateUint16Array(a){return array=void 0!=self.Uint16Array?new Uint16Array(a):Array(a)};
